### ISSUE TITLE
Running src/fill_database.py before the first run start.sh causes an error

### ISSUE THREAD

**Issue by NLeech** [NLeech/School-management#1]
Running src/fill_database.py before the first run start.sh causes an error:
Traceback (most recent call last):
  File "/home/leech/Docker/School-management/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/leech/Docker/School-management/env/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/leech/Docker/School-management/env/lib/python3.10/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "groups" does not exist
LINE 1: INSERT INTO groups (id, name) VALUES (nextval('group_id_seq'...

**Comment by NLeech** [comment]
Fixed in dev.
